import React from 'react'
import {Container, Row, Col} from 'react-bootstrap';

const About = () => {
  return (
    <Container style={{marginTop:'50px'}}> 
        <h1>Qui somme-nous?</h1>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia ipsum similique, sint, ad eos beatae rerum fuga ut dolorum aliquam, numquam eligendi dolor blanditiis a magnam! Adipisci expedita soluta maiores officia maxime quia harum vero ducimus consectetur cumque sint, laboriosam nulla nam debitis recusandae. Eaque, quam harum dolor sequi consequatur aliquam minus officiis dolorem atque necessitatibus. Natus architecto sapiente, dolore culpa odio dignissimos expedita aut. Id tempora reprehenderit, distinctio mollitia similique voluptatum sequi corporis hic, itaque illo quisquam incidunt optio veniam nostrum ad reiciendis necessitatibus iste dolorum voluptates velit unde voluptas praesentium totam ipsam! Enim voluptate, cumque aliquid ipsam distinctio, officiis vitae recusandae voluptatum perspiciatis obcaecati iure sit consequatur corrupti. Dicta repellendus blanditiis repudiandae animi pariatur molestiae officiis aliquid facere, autem quis ipsum unde vero vel, ullam expedita eos provident eligendi! Non adipisci ducimus alias vel, officia quibusdam aliquid eum a, earum nobis vero similique consectetur corrupti accusantium aut aliquam! Explicabo tempora corporis officia minus eaque soluta aspernatur animi ut asperiores, necessitatibus, exercitationem quaerat quod ea perferendis commodi. Sint, officiis distinctio suscipit iusto tempora error ratione corporis nisi cumque, sit asperiores aspernatur quisquam fugit obcaecati aliquam quo magnam? Hic dolore soluta magnam vero nobis quidem assumenda nostrum, sunt debitis dolor.</p>
        <h1>Notre Spécialité</h1>
        <Row>
            <Col md={6}>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet consequuntur esse temporibus? Neque, nam incidunt! Assumenda labore quaerat sint! Tenetur eos dolores nemo. Esse veniam accusamus eligendi animi alias voluptas blanditiis obcaecati temporibus? Tenetur ratione nemo porro eveniet eius nam at illo soluta sapiente ducimus, ut, quidem voluptas vel, neque blanditiis facilis voluptates laudantium obcaecati? Aut quae porro amet reprehenderit. Nisi inventore fugiat tempore autem nostrum cumque aperiam dolorum error nobis, eaque ea veritatis, officia illo deserunt explicabo omnis voluptatum repellat dolor qui quae voluptas neque, porro reprehenderit impedit! Voluptates modi, quos doloremque sequi dolores voluptatum ab ullam aliquam temporibus illo a dolore quis ipsa magnam obcaecati ipsam dignissimos exercitationem magni dolor sunt cupiditate praesentium adipisci repudiandae facilis. Quaerat earum eos, ipsa aperiam nemo tempora officia ipsam tempore aliquid minus, quas assumenda. Voluptatum minus provident delectus pariatur animi facere cumque velit, dicta eligendi accusamus sunt magni expedita. Accusamus vitae facilis deserunt ab quis sit maxime illo accusantium placeat molestiae, deleniti optio impedit, ullam, provident facere amet qui? Perspiciatis magnam quos ipsa ea recusandae animi fugit veniam tempora quidem minima, neque aliquid, debitis praesentium maiores. Amet hic commodi vel molestias quo, dolore tenetur, quasi minus impedit atque dolorem officiis ipsam fugit.</p>
            </Col>
            <Col md={6}>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Debitis vero, laborum repellendus ipsum incidunt doloremque dicta mollitia tenetur, sint maxime quis alias quo asperiores porro iure dolores vel, dolore consequuntur praesentium neque dolorem. Esse optio iusto, dicta dolores quam debitis perferendis illum facilis corporis odio necessitatibus, nesciunt adipisci harum enim, animi earum! In quod dolor vero rerum, rem enim! Temporibus sapiente earum ratione, dolores exercitationem veritatis nesciunt dignissimos esse perspiciatis tenetur nam incidunt nihil eius officia dicta id magni tempora neque fugiat aut repellat atque maxime. Vero ipsum ad, animi consectetur obcaecati molestiae unde dicta, accusantium culpa ipsam nisi molestias deserunt quisquam reprehenderit harum fugiat excepturi sequi eligendi corporis eveniet expedita iste exercitationem cumque. Unde non eaque ex laboriosam distinctio, accusamus eius suscipit, tempore vero repellendus magni sunt illo illum exercitationem fugiat itaque obcaecati a quam ducimus maiores. Culpa assumenda dolore quaerat pariatur, ex quae fugit eos libero ea quisquam molestias! Explicabo pariatur repellendus aut, a animi vitae aliquam facilis dolores ipsam exercitationem. Quaerat facere ipsum deserunt quisquam ut! Fugit illo reprehenderit eveniet autem nihil libero, et, voluptatem quae porro commodi, dolorum suscipit molestiae iste impedit amet iusto? Eligendi saepe asperiores consequuntur maxime impedit earum iure doloremque nemo officia in!</p>
            </Col>
        </Row>
        <Row>
            <h1>Le Chef</h1>
            <Col md={3}>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Impedit quia suscipit itaque quod alias expedita autem blanditiis harum, quos, asperiores culpa ut vitae corporis voluptatum tenetur aliquam. Quidem culpa excepturi recusandae voluptatibus voluptates consequuntur magni similique repellat consectetur sapiente aliquid qui non maiores pariatur vitae ipsum sunt rem voluptatum voluptatem voluptate, quas ea repudiandae? Cum beatae ipsum nostrum nobis iste nisi voluptas blanditiis quibusdam a nulla. Illum fugit, quaerat sunt itaque reiciendis libero sed minima, quibusdam, debitis animi qui tempora ratione eaque cumque nesciunt sint placeat minus omnis! Soluta voluptatibus odit explicabo voluptate corporis vero placeat minus cum sequi deserunt.</p>
            </Col>
            <Col md={3}>
                <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cumque temporibus repellendus, mollitia, ad numquam exercitationem repellat ipsum eius quis eos libero obcaecati, amet sint itaque laboriosam. Officia at saepe placeat nam blanditiis ratione nesciunt itaque, quibusdam temporibus debitis est cumque. Ipsum expedita asperiores accusamus dolorum adipisci eligendi est dignissimos ea laboriosam! Inventore quibusdam dolor impedit itaque voluptates. Eius adipisci repellendus, sint laudantium ad non temporibus ipsam et suscipit doloremque perspiciatis nemo provident similique quaerat possimus! Blanditiis, molestiae? Omnis, a qui tempore vero at porro veritatis voluptate quae commodi, maxime deserunt perferendis! Necessitatibus provident sed atque eaque qui delectus ipsa dignissimos?</p>
            </Col>
            <Col md={3}>
                <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Animi harum cumque eius aliquid esse incidunt deserunt. Reprehenderit quidem quis maiores quia quam ipsa fugiat adipisci voluptas provident eos, odit consectetur sunt officiis, pariatur natus quod dolore magnam ratione repudiandae totam vero corrupti inventore minima in. Suscipit libero cupiditate, quia dolorum voluptatum officia ex placeat modi ullam pariatur vero voluptatem eveniet consequuntur aperiam consequatur laboriosam officiis mollitia soluta? Nostrum temporibus sit, sed non, sint ullam labore obcaecati neque nobis asperiores ipsam beatae accusantium repudiandae eveniet soluta magni voluptates suscipit in qui aliquid. Quasi est provident consectetur suscipit cumque ad explicabo facere!</p>
            </Col>
            <Col md={3}>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni mollitia excepturi beatae tempore. Esse vitae eos eligendi, mollitia cum, placeat voluptatem, doloribus pariatur temporibus molestiae quam illum. Veniam aut, corporis recusandae asperiores nemo quasi nulla debitis voluptates id est natus adipisci fuga odio. Enim, fuga harum animi molestias officiis quasi nobis nesciunt suscipit ipsum in pariatur error vitae vero explicabo repellendus amet ipsam dicta modi debitis. Odio officia nemo quod numquam repudiandae velit totam assumenda voluptatem, ea harum reprehenderit molestias, tempore rerum sit natus. Earum dolorem adipisci eaque blanditiis non maiores, consequatur officiis magni corrupti unde accusantium. Vitae, magni minus!</p>
            </Col>
        </Row>

    </Container>
  )
}

export default About